version: '3.8'

networks:
  default:

services:

  mysql-db:
    container_name:  mysql-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysql-volume:/var/lib/mysql:rw
      - ./mysql-db:/docker-entrypoint-initdb.d/
    networks:
      - default

  server:
    container_name: server
    depends_on:
      - mysql-db
    build: ./server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NESTJS_APP_LOCAL_PORT:$NESTJS_APP_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - default

  client:
    container_name: client
    depends_on: 
      - server
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NEXTJS_APP_LOCAL_PORT:$NEXTJS_APP_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    networks:
      - default

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes: 
  mysql-volume: